name: Print Environment Variables

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  print_variables:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "Hello, this is a ENV VAR"
    steps:
      - name: Checkout my repository
        uses: actions/checkout@v3

      - name: Print environment variable
        run: |
          echo "Environment variable: $MY_ENV_VAR"

      - name: Print secret environment
        env:
          MY_SECRET_VAR: ${{ secrets.MY_SECRET_VAR }}
        run: |
          echo "Secret environment: $MY_SECRET_VAR"
